version: "3.8"
services:
  store_service_container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
        - .:/app
    depends_on:
     - store_db_container

  store_db_container:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: store_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306
